apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
  labels:
    app: nginx-deployment-2
spec:
   replicas: 3
   selector:
     matchLabels:
       app: nginx-deployment-2
   template:
     metadata:
       labels:
         app: nginx-deployment-2
     spec:
       containers:
       - name: nginx-deployment-2
         image: nginx:1.16
         ports:
         - containerPort: 8080