apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.appName } }
spec:
  selector:
    matchLabels:
      app: { { .Values.appName } }
  template:
    metadata:
      labels:
        app: { { .Values.appName } }
  spec:
    containers:
      - name: { { .Values.appName } }
        image: xxx
        ports:
          - containerPort: xxx
