---
apiVersion: v1
kind: Service
metadata:
  name: { { .Values.appName } }
spec:
  selector:
    type: { { .Values.serviceType } }
    app: { { .Values.appName } }
  ports:
    - protocol: TCP
      port: { { .Values.servicePort } }
      targetPort: { { .Values.containerPort } }
